import type { NextPage } from 'next'
import Head from 'next/head'
import dynamic from 'next/dynamic';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';

const Map = dynamic(() => import('../components/map'), { ssr: false });

const Home: NextPage = () => {

    return (
        <Box sx={{ p: 15 }}>
            <Head>
                <title>JKH</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Typography variant="h3" component="h1">Hi there, jkh app in the future</Typography>
            <Map />
        </Box>
    )
}

export default Home
